### PR TITLE
Rigify related fixes for issue #21

### PR DESCRIPTION
**Pull request by angavrilov**
I updated weights, so I think it's time to start checking or reviewing this. Here are the main things changed here:

* A few advanced strategies are added for tricky cases of binding bone positions to the mesh. They can only be accessed by manually editing the json file.
* The Load/Save Rig operators on the Developer panel will remember the strategies in custom properties of bones and reuse them when saving unless the automatically chosen strategy is clearly better. The regular non-developer apply rig operators don't create these properties, so the data will be lost if you try to re-save.
* The json file can now record B-Bone settings and constraints for 'ad-hoc' rigging of helper bones.
* The Rigify metarig is updated to fix bone positioning and adjust settings. A few rigged helper bones are added to improve joint deformation.
* Many FK bones are switched from Quaternion to various Euler orders.
* The Add Rigify Rig operator automatically invokes conversion to the new style face. This fixes the teeth issue and should make the teeth hack option obsolete, but I only disabled the option without deleting it for now (it's quite likely broken however).
* I updated all weights to match metarig changes, including the new helpers; I also did a pass on all weights (unless I missed something) to fix obvious issues, smooth gradients, etc.

### CODE REVIEW

**Comment by joepal1976** [comment]
Thank you. So far, I've read through the commits to understand what they do. I'll check out the PR branch locally and do some testing too, but so far I see no reason against merging.

Concerning the normalization of euler rotation to XYZ for certain bones... Are there any relevant bones left which has a different rotation mode? At some point during the spring, I switched to using XYZ euler whereever I could think of in the other rigs, in order to be able to know beforehand which rotation mode everything use when storing/reloading poses.

**Comment by angavrilov** [comment]
Well, I left limb base bones (thigh, upper_arm) as Quaternion because of the wide range of motion (Euler is best for constrained joints), and used different orders for shoulder and hand bones (which I think may work better, but it is a point for discussion).

Also, the jaw_master control remains Quaternion as well, even though it could be XYZ without problems; but since it is created by the face upgrade operator it has to be changed in code, either in Rigify itself or the Add Rigify Rig operator.

**Comment by angavrilov** [comment]
Btw I added a couple more commits with small fixes for things I forgot about but noticed now.

**Comment by angavrilov** [comment]
Sorry for the noise, but I did a force push because I decided to improve mouth corner joint position and weighting, which changed the weights file a lot (I did a Normalize All) and I thought it's better to only keep one weight update commit to save disk space.

**Comment by joepal1976** [comment]
That's no problem at all. Getting this rigify fix in place is lifting a very heavy weight off my shoulders, as I'm very far from read up on all the finer details. It would have taken me ages to do these things, if I had succeeded at all.

Anyway, I've done some testing now, and I still see no reason against merging. So I'll merge now to get it in place and if there's anything more that should get in we can take that in another PR.

**Comment by joepal1976** [comment]
@angavrilov : I've updated the preliminary release notes for the next release of MPFB2 at http://static.makehumancommunity.org/mpfb/releases/release_20a2.html (editable source is at https://github.com/makehumancommunity/makehuman-static-website/blob/master/content/MPFB/Releases/release_20a2.md).

Can you check if you agree with the description of the rigify update?

**Comment by angavrilov** [comment]
It seems OK.

There are a couple of issues that may be easier to be fixed by you maybe, because it's MPFB specific stuff rather than rigify as such:

* Make the rigify generate panel somehow recognize rigify-targeted rigs loaded through the developer panel, and not only the add rigify rig one. Basically ensure it's possible to add and generate a working rigify rig via the developer panel tools.
* Add a dropdown to select rigify rig types like with the regular ones - I think it's worth it to at least add a 'with toes' version, and maybe even one with even more helpers (the hip area especially is very bad in extreme poses without additional stuff).

**Comment by joepal1976** [comment]
Ok, thanks. I've written issues for these for now so I remember them.

**Pull request merged**
