### PR TITLE
Improve deformations of the Rigify rig.

### PR DESCRIPTION
**Pull request by angavrilov**
This adjusts a number of thing to improve deformations produced by the Rigify rig.

- Align leg bones to world X and switch to manual rotation axis.
- Mix some of the upper arm twist rotation into the shoulder helper.
- Add helpers to control deformation of the front hip fold area.
- Tweak transformation constraint rotations of the pelvis helpers.
- Add transformation constraint scaling to the knee and elbow helpers.
- Apply Preserve Volume to fingers using a second Armature modifier with a mask.

Additionally, a version of the rig with toes is implemented, and a number of technical changes are made. 

Also, here is the [blender file](https://www.dropbox.com/s/3sdwkrivyoguwyi/rigify-rig-paint.20021017.blend?dl=0) used to save the weights (requires 3.4 alpha).

### CODE REVIEW

**Comment by joepal1976** [comment]
Thanks. Having tested this on a few scenarios, I think it looks fine. And I especially like the ensure armature addition to rigservice.

**Comment by angavrilov** [comment]
Save a copy of the blend file too just in case. It uses geometry nodes to layer helper weights in a way that can be toggled on or off for comparison during painting, and ensures the helpers get an exact 50/50 split of weight from the original bone groups - i.e. the weights in the json files are effectively flattened/baked rather than how I painted them.

**Comment by joepal1976** [comment]
I've put the blend file in a new LFS repository and invited you with write access. I intend to put my own source data blends here eventually, in order to get some form of version control. I'll keep the repo private until I've finished up the basic structure.

Note the CC0 license text in the root of the repo, per the promise that all assets are CC0 in MPFB. If you think this is in error, let me know.

**Comment by angavrilov** [comment]
@joepal1976 another question is whether you considered/planned adding the corrective smooth modifier to the mesh at some point? There is of course a big difficulty because of the shape keys - to get it to properly work for posing you have to use the bind mode and bind to the unposed body but with the shape keys active.

But the main reason I ask is I think it may be useful to paint a 'no smooth' mask vertex group to restrict it affecting certain areas, but it seems weird to have the mask without a modifier.

**Comment by joepal1976** [comment]
@angavrilov I haven't really gotten very far with any plan regarding this. I know there are deformations that are very obviously suboptimal, but so far my experiments with solving these areas have been pretty disappointing too. 

I realize that as far as answers go, this is pretty vague. But what I can say is that is that I don't plan on doing anything about this in the near term, as there are too many other things which are higher up on the to do list.

**Pull request merged**
